In [1]:
import numpy as np

In [192]:
import numpy as np

cities_len = 1000
def shuffle(path:np.ndarray)->None:
    np.random.shuffle(path[1:cities_len])

def shuffle_partially(path:np.ndarray)->None:
    part = np.random.choice(cities_len, 2)+1
    if part[0] < part[1]:
        np.random.shuffle(path[part[0]:part[1]])
    else:
        np.random.shuffle(path[1:part[0]])
        np.random.shuffle(path[part[1]:cities_len])

#path = np.append(np.arange(cities_len), [0])
#path[1:cities_len]
#np.random.shuffle(path[1:cities_len])
shuffle_partially(path)
path

array([  0, 146, 289, ..., 894, 763,   0])

In [190]:
best = path
best

array([  0, 747, 518, ..., 971,  83,   0])

In [198]:
best

array([  0, 146, 289, ..., 894, 763,   0])

In [5]:
a = np.arange(10)
far = a >a.mean()
b = a[far]
np.random.shuffle(b)
a[far] = b
a
np.argmin(a)

0

In [6]:
import pandas as pd
import numpy as np

cities = pd.read_csv("../input/cities.csv")
cities_xy = np.stack((cities.X.values, cities.Y.values), axis=1)
cities_xy[:5]

array([[ 316.83673906, 2202.34070734],
       [4377.40597217,  336.60208217],
       [3454.15819771, 2820.05301125],
       [4688.09929763, 2935.89805581],
       [1010.69695175, 3236.75098903]])

In [2]:
def get_score(path):
    xy = cities_xy[path]
    return np.linalg.norm(xy-np.roll(xy, -1, axis=0), axis=1).sum()
    #prime_value = (values[9::10] * [int(isprime(i)==False)*0.1 for i in path[9::10]]).sum()
    #return values.sum() + prime_value

In [3]:
path = np.arange(5)
get_score(path)

13292.829911567696

In [6]:
import pandas as pd
path = pd.read_csv('../input/sample_submission.csv')
path = path['Path'].values
len(path)

197770

In [6]:
a = np.arange(5)
a[1], a[2] = a[2], a[1]

In [12]:
from itertools import permutations

for item in permutations(a, len(a)):
    print(item)

(0, 2, 1, 3, 4)
(0, 2, 1, 4, 3)
(0, 2, 3, 1, 4)
(0, 2, 3, 4, 1)
(0, 2, 4, 1, 3)
(0, 2, 4, 3, 1)
(0, 1, 2, 3, 4)
(0, 1, 2, 4, 3)
(0, 1, 3, 2, 4)
(0, 1, 3, 4, 2)
(0, 1, 4, 2, 3)
(0, 1, 4, 3, 2)
(0, 3, 2, 1, 4)
(0, 3, 2, 4, 1)
(0, 3, 1, 2, 4)
(0, 3, 1, 4, 2)
(0, 3, 4, 2, 1)
(0, 3, 4, 1, 2)
(0, 4, 2, 1, 3)
(0, 4, 2, 3, 1)
(0, 4, 1, 2, 3)
(0, 4, 1, 3, 2)
(0, 4, 3, 2, 1)
(0, 4, 3, 1, 2)
(2, 0, 1, 3, 4)
(2, 0, 1, 4, 3)
(2, 0, 3, 1, 4)
(2, 0, 3, 4, 1)
(2, 0, 4, 1, 3)
(2, 0, 4, 3, 1)
(2, 1, 0, 3, 4)
(2, 1, 0, 4, 3)
(2, 1, 3, 0, 4)
(2, 1, 3, 4, 0)
(2, 1, 4, 0, 3)
(2, 1, 4, 3, 0)
(2, 3, 0, 1, 4)
(2, 3, 0, 4, 1)
(2, 3, 1, 0, 4)
(2, 3, 1, 4, 0)
(2, 3, 4, 0, 1)
(2, 3, 4, 1, 0)
(2, 4, 0, 1, 3)
(2, 4, 0, 3, 1)
(2, 4, 1, 0, 3)
(2, 4, 1, 3, 0)
(2, 4, 3, 0, 1)
(2, 4, 3, 1, 0)
(1, 0, 2, 3, 4)
(1, 0, 2, 4, 3)
(1, 0, 3, 2, 4)
(1, 0, 3, 4, 2)
(1, 0, 4, 2, 3)
(1, 0, 4, 3, 2)
(1, 2, 0, 3, 4)
(1, 2, 0, 4, 3)
(1, 2, 3, 0, 4)
(1, 2, 3, 4, 0)
(1, 2, 4, 0, 3)
(1, 2, 4, 3, 0)
(1, 3, 0, 2, 4)
(1, 3, 0, 4, 2)
(1, 3, 2

In [8]:
cities_len = len(cities)
shuffle_len = 6
start_index = np.random.choice(cities_len-shuffle_len)
score_start_index = start_index - start_index%10
pm_start_index = start_index%10
#     small_path = path[score_start_index : start_index + shuffle_len + 2]
#     score = get_score(small_path)

In [9]:
path = np.append(np.arange(cities_len), [0])
print('start_index:', start_index,  path [start_index])
print('score_start_index:', score_start_index, path [score_start_index])
print('pm_start_index:', pm_start_index)
small = path[start_index : start_index + shuffle_len]
small_start = path[score_start_index:start_index]
small_end = path[start_index + shuffle_len:start_index + shuffle_len+1]

# small_path = path[score_start_index : start_index + shuffle_len + 2]
# small_path
#     score = get_score(small_path)
small_start

start_index: 41173 41173
score_start_index: 41170 41170
pm_start_index: 3


array([41170, 41171, 41172])

In [40]:
for item in permutations(small):
    print(np.concatenate((small_start, item, small_end)))

[161130 161131 161132 161133 161134 161135 161136 161137 161138 161139
 161140 161141 161142]
[161130 161131 161132 161133 161134 161135 161136 161137 161138 161139
 161141 161140 161142]
[161130 161131 161132 161133 161134 161135 161136 161137 161138 161140
 161139 161141 161142]
[161130 161131 161132 161133 161134 161135 161136 161137 161138 161140
 161141 161139 161142]
[161130 161131 161132 161133 161134 161135 161136 161137 161138 161141
 161139 161140 161142]
[161130 161131 161132 161133 161134 161135 161136 161137 161138 161141
 161140 161139 161142]
[161130 161131 161132 161133 161134 161135 161136 161137 161139 161138
 161140 161141 161142]
[161130 161131 161132 161133 161134 161135 161136 161137 161139 161138
 161141 161140 161142]
[161130 161131 161132 161133 161134 161135 161136 161137 161139 161140
 161138 161141 161142]
[161130 161131 161132 161133 161134 161135 161136 161137 161139 161140
 161141 161138 161142]
[161130 161131 161132 161133 161134 161135 161136 161137 161

In [11]:
print(small)
a = small.reshape((-1,2))
a

[41173 41174 41175 41176 41177 41178]


array([[41173, 41174],
       [41175, 41176],
       [41177, 41178]])

In [55]:
for item in permutations(a):
    print(np.concatenate(item))

[161136 161137 161138 161139 161140 161141]
[161136 161137 161140 161141 161138 161139]
[161138 161139 161136 161137 161140 161141]
[161138 161139 161140 161141 161136 161137]
[161140 161141 161136 161137 161138 161139]
[161140 161141 161138 161139 161136 161137]


In [59]:
seq_len = 6
print(int(cities_len/seq_len))
#band_cnt = np.random.choice(int(cities_len/seq_len))
print(band_cnt)
#start_index = np.random.choice(cities_len/band_cnt-seq_len)*cities_len+1

32961
28277


In [10]:
xy = cities_xy[path]
values = np.linalg.norm(xy-xy[0], axis=1)
values = values[:-1]
index = np.argsort(values)
path[index]

array([     0,  78934,  47239, ...,  85574,   9278, 146798], dtype=int64)

In [5]:
a = np.array([1,2,4])
a.size

3